services:
  app:
    build: ./horrible-app
    restart: unless-stopped
    deploy:
      replicas: 3

  lb:
    image: caddy
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./lb/Caddyfile:/etc/caddy/Caddyfile:ro
