services:
  app:
    build: ./horrible-app
    restart: unless-stopped
    labels:
      - com.example.node-app=true
    deploy:
      replicas: 3
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  autoheal:
    image: willfarrell/autoheal
    restart: always
    labels:
      - com.example.node-app=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - AUTOHEAL_CONTAINER_LABEL=com.example.node-app
    
  lb:
    build: ./lb
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./lb/Caddyfile:/etc/caddy/Caddyfile:ro
    healthcheck:
      test: curl -f http://localhost/health-check || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

